#server:
#  port: 8801
#
#spring:
#  cloud:
#    bus:
#      enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    host: 192.168.1.200
#    port: 5672
#    username: admin
#    password: admin
#  sleuth:
#    sampler:
#      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411
#    sender:
#      type: rabbit
#
#hadoop:
#  node-url: hdfs://192.168.1.200:9000
#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details: always